export type PhotoPackCategory = 'social' | 'dating' | 'business' | 'travel' | 'fashion' | 'lifestyle';

export type PhotoPackPricing = {
  hd: {
    tokens: number;
    rubles: number;
  };
  fullHd: {
    tokens: number;
    rubles: number;
  };
};

export type PhotoPack = {
  id: string;
  slug: string;
  title: string;
  description: string;
  summary: string;
  photos: number;
  price: string;
  photoCount: 2 | 4 | 5 | 6 | 8;
  priceRub: number;
  priceCrystals: number;
  pricing: PhotoPackPricing;
  category: PhotoPackCategory;
  categoryLabel: string;
  image: string;
  gallery: string[];
  suitableFor: string[];
  features: string[];
  deliverables: string[];
};

const sharedFeatures = [
  '20 профессиональных фото',
  '1-3 исходных селфи',
  'готово за несколько минут',
  'реалистичная обработка',
];

const legacyBasePhotoPacks: Omit<PhotoPack, 'pricing' | 'photoCount' | 'priceRub' | 'priceCrystals'>[] = [
  {
    id: 'career',
    slug: 'career',
    title: 'Бизнес-портрет',
    description: 'LinkedIn, резюме и рабочие профили',
    summary: 'Уверенная деловая фотосессия для LinkedIn, резюме, сайта компании и личного бренда.',
    photos: 20,
    price: '790 ₽',
    category: 'business',
    categoryLabel: 'Бизнес',
    image: '/career-woman-blazer.png',
    gallery: ['/career-woman-blazer.png', '/career-woman-1.png', '/career-woman-2.png', '/studio-white-suit.png'],
    suitableFor: ['LinkedIn', 'Резюме', 'Работа', 'Личный бренд', 'Сайт компании'],
    features: sharedFeatures,
    deliverables: ['Портрет', 'По пояс', 'Рабочий кадр', 'Профиль'],
  },
  {
    id: 'dating',
    slug: 'dating',
    title: 'Знакомства',
    description: 'Притягательные фото для dating и соцсетей',
    summary: 'Живая, теплая серия для анкет знакомств, соцсетей и естественного первого впечатления.',
    photos: 20,
    price: '790 ₽',
    category: 'dating',
    categoryLabel: 'Свидания',
    image: '/package-previews/sp004-cozy-cafe.jpg',
    gallery: ['/package-previews/sp004-cozy-cafe.jpg', '/dating-woman-1.png', '/dating-woman-2.png', '/dating-woman-mirror.png'],
    suitableFor: ['Dating', 'Соцсети', 'Анкета', 'Личный бренд', 'Новые фото'],
    features: sharedFeatures,
    deliverables: ['Портрет', 'Улыбка', 'Lifestyle', 'Анкета'],
  },
  {
    id: 'sup',
    slug: 'sup',
    title: 'SUP Editorial',
    description: 'Luxury editorial съемка на воде',
    summary: 'Кинематографичная серия на воде для отпуска, соцсетей и яркого lifestyle-образа.',
    photos: 20,
    price: '790 ₽',
    category: 'travel',
    categoryLabel: 'Путешествия',
    image: '/package-previews/sp005-sup-editorial.jpg',
    gallery: ['/package-previews/sp005-sup-editorial.jpg', '/package-previews/sp005-sup-editorial-board.jpg', '/package-previews/sp005-sup-editorial-lifestyle.jpg', '/studio-nature.png'],
    suitableFor: ['Путешествия', 'Соцсети', 'Лето', 'Lifestyle', 'Контент'],
    features: sharedFeatures,
    deliverables: ['Портрет', 'На воде', 'Lifestyle', 'Широкий кадр'],
  },
  {
    id: 'studio-elegance',
    slug: 'studio-elegance',
    title: 'Studio Elegance',
    description: 'Теплая премиальная студийная серия',
    summary: 'Премиальная студийная фотосессия для портфолио, соцсетей и личного бренда.',
    photos: 20,
    price: '790 ₽',
    category: 'fashion',
    categoryLabel: 'Fashion',
    image: '/package-previews/sp006-studio-elegance.jpg',
    gallery: ['/package-previews/sp006-studio-elegance.jpg', '/studio-glamour.png', '/studio-fashion.png', '/studio-white-suit.png'],
    suitableFor: ['Портфолио', 'Соцсети', 'Личный бренд', 'Анкета', 'Подарок'],
    features: sharedFeatures,
    deliverables: ['Портрет', 'По пояс', '3/4', 'Полный рост'],
  },
  {
    id: 'lakeside-walk',
    slug: 'lakeside-walk',
    title: 'Lakeside Walk',
    description: 'Романтичная прогулка у озера',
    summary: 'Мягкая прогулочная серия для соцсетей, знакомств и спокойного романтичного настроения.',
    photos: 20,
    price: '790 ₽',
    category: 'dating',
    categoryLabel: 'Свидания',
    image: '/package-previews/sp007-lakeside-walk.jpg',
    gallery: ['/package-previews/sp007-lakeside-walk.jpg', '/studio-nature.png', '/dating-woman-3.png', '/social-woman-2.png'],
    suitableFor: ['Dating', 'Прогулка', 'Соцсети', 'Личный архив', 'Lifestyle'],
    features: sharedFeatures,
    deliverables: ['Портрет', 'Прогулка', 'Средний план', 'Lifestyle'],
  },
  {
    id: 'casual-park',
    slug: 'casual-park',
    title: 'Casual Park',
    description: 'Естественный quiet luxury в парке',
    summary: 'Естественная lifestyle-серия с дорогим, спокойным настроением для повседневного контента.',
    photos: 20,
    price: '790 ₽',
    category: 'lifestyle',
    categoryLabel: 'Lifestyle',
    image: '/package-previews/sp008-quiet-luxury-park.jpg',
    gallery: ['/package-previews/sp008-quiet-luxury-park.jpg', '/social-woman-1.png', '/social-woman-2.png', '/social-woman-cafe.png'],
    suitableFor: ['Lifestyle', 'Соцсети', 'Личный бренд', 'Контент', 'Профиль'],
    features: sharedFeatures,
    deliverables: ['Портрет', 'Прогулка', 'Кафе', 'Город'],
  },
  {
    id: 'minimal-black-studio',
    slug: 'minimal-black-studio',
    title: 'Minimal Black Studio',
    description: 'Минималистичный студийный портрет',
    summary: 'Сдержанный студийный портрет с сильным контрастом для деловых и персональных профилей.',
    photos: 20,
    price: '790 ₽',
    category: 'business',
    categoryLabel: 'Бизнес',
    image: '/studio-bw-man.png',
    gallery: ['/studio-bw-man.png', '/career-man-1.png', '/career-man-editorial.png', '/ref-bw-blinds.png'],
    suitableFor: ['Профиль', 'Бизнес', 'Портфолио', 'Резюме', 'Личный бренд'],
    features: sharedFeatures,
    deliverables: ['Портрет', 'Профиль', 'Черный фон', 'Editorial'],
  },
  {
    id: 'russian-editorial',
    slug: 'russian-editorial',
    title: 'Russian Editorial',
    description: 'Дизайнерский editorial с красным акцентом',
    summary: 'Выразительная fashion-серия с редакторским светом и акцентным настроением.',
    photos: 20,
    price: '790 ₽',
    category: 'fashion',
    categoryLabel: 'Fashion',
    image: '/studio-red-light-v2.png',
    gallery: ['/studio-red-light-v2.png', '/studio-glamour.png', '/ref-neon.png', '/studio-fashion.png'],
    suitableFor: ['Fashion', 'Портфолио', 'Обложка', 'Соцсети', 'Креатив'],
    features: sharedFeatures,
    deliverables: ['Портрет', 'Editorial', 'Акцентный свет', 'Образ'],
  },
  {
    id: 'social',
    slug: 'social',
    title: 'Лайфстайл',
    description: 'Стильные городские образы на каждый день',
    summary: 'Городская серия для соцсетей, личного бренда и естественного визуального обновления.',
    photos: 20,
    price: '790 ₽',
    category: 'social',
    categoryLabel: 'Соцсети',
    image: '/social-woman-1.png',
    gallery: ['/social-woman-1.png', '/social-woman-2.png', '/social-woman-3.png', '/social-woman-car.png'],
    suitableFor: ['Соцсети', 'Профиль', 'Контент', 'Личный бренд', 'Lifestyle'],
    features: sharedFeatures,
    deliverables: ['Портрет', 'Город', 'Кафе', 'Прогулка'],
  },
  {
    id: 'studio',
    slug: 'studio',
    title: 'Студийный свет',
    description: 'Профессиональное освещение и минимализм',
    summary: 'Чистая студийная серия с профессиональным светом для деловых и личных задач.',
    photos: 20,
    price: '790 ₽',
    category: 'business',
    categoryLabel: 'Бизнес',
    image: '/studio-white-suit.png',
    gallery: ['/studio-white-suit.png', '/career-woman-1.png', '/studio-stool-woman.png', '/career-woman-3.png'],
    suitableFor: ['Бизнес', 'Портфолио', 'Резюме', 'Соцсети', 'Личный бренд'],
    features: sharedFeatures,
    deliverables: ['Портрет', 'По пояс', 'Полный рост', 'Профиль'],
  },
  {
    id: 'neon',
    slug: 'neon',
    title: 'Неон и Арт',
    description: 'Креативные образы с ярким светом',
    summary: 'Артовая серия с неоновым светом для яркого профиля, афиши или креативного портфолио.',
    photos: 20,
    price: '790 ₽',
    category: 'fashion',
    categoryLabel: 'Fashion',
    image: '/ref-neon.png',
    gallery: ['/ref-neon.png', '/studio-red-light-v2.png', '/ref-vintage.png', '/studio-fashion.png'],
    suitableFor: ['Креатив', 'Fashion', 'Соцсети', 'Портфолио', 'Афиша'],
    features: sharedFeatures,
    deliverables: ['Портрет', 'Неон', 'Арт', 'Editorial'],
  },
  {
    id: 'bw',
    slug: 'bw',
    title: 'Черно-белое',
    description: 'Классическая эстетика и глубина',
    summary: 'Лаконичная черно-белая серия для портфолио, личного бренда и выразительного профиля.',
    photos: 20,
    price: '790 ₽',
    category: 'fashion',
    categoryLabel: 'Fashion',
    image: '/ref-bw-blinds.png',
    gallery: ['/ref-bw-blinds.png', '/studio-bw-man.png', '/studio-glamour.png', '/career-man-editorial.png'],
    suitableFor: ['Портфолио', 'Fashion', 'Профиль', 'Личный бренд', 'Классика'],
    features: sharedFeatures,
    deliverables: ['Портрет', 'Контраст', 'Editorial', 'Профиль'],
  },
];

const currentBasePhotoPacks: Omit<PhotoPack, 'pricing' | 'photoCount' | 'priceRub' | 'priceCrystals'>[] = [
  {
    id: 'autumn-promenade',
    slug: 'autumn-promenade',
    title: 'Осенний променад',
    description: 'Кинематографичная прогулка в золотом осеннем парке',
    summary: 'Четыре связанных fashion-кадра в чёрном пальто среди золотой листвы: прогулка, портрет на скамье, живой поворот и спокойный финал.',
    photos: 4,
    price: '189 ₽',
    category: 'lifestyle',
    categoryLabel: 'Lifestyle',
    image: '/package-previews/sp011-autumn-promenade-model-a-hc001.jpg',
    gallery: [
      '/package-previews/sp011-autumn-promenade-model-a-hc001.jpg',
      '/package-previews/sp011-autumn-promenade-model-a-hc002.jpg',
      '/package-previews/sp011-autumn-promenade-model-a-hc003.jpg',
      '/package-previews/sp011-autumn-promenade-model-a-hc004.jpg',
    ],
    suitableFor: ['Соцсети', 'Личный бренд', 'Осенний контент', 'Профиль'],
    features: ['4 профессиональных фото', 'Один цельный образ', 'Живая осенняя серия', 'Сохранение внешности'],
    deliverables: ['Прогулочный кадр', 'Портрет на скамье', 'Поворот через плечо', 'Стоящий портрет'],
  },
  {
    id: 'misty-morning',
    slug: 'misty-morning',
    title: 'Туманное утро',
    description: 'Тихая полевая серия в прохладном рассеянном свете',
    summary: 'Мягкая кинематографичная фотосессия в поле: спокойный портрет, близкий кадр, ветер в волосах и естественная поза среди трав.',
    photos: 4,
    price: '189 ₽',
    category: 'lifestyle',
    categoryLabel: 'Lifestyle',
    image: '/package-previews/sp012-misty-morning-model-a-hc001.jpg',
    gallery: [
      '/package-previews/sp012-misty-morning-model-a-hc001.jpg',
      '/package-previews/sp012-misty-morning-model-a-hc002.jpg',
      '/package-previews/sp012-misty-morning-model-a-hc003.jpg',
      '/package-previews/sp012-misty-morning-model-a-hc004.jpg',
    ],
    suitableFor: ['Соцсети', 'Личный архив', 'Личный бренд', 'Спокойный lifestyle'],
    features: ['4 профессиональных фото', 'Один цельный образ', 'Мягкая естественная мимика', 'Сохранение внешности'],
    deliverables: ['Главный портрет', 'Крупный портрет', 'Кадр с ветром', 'Портрет среди трав'],
  },
  {
    id: 'golden-field',
    slug: 'golden-field',
    title: 'Золотое поле',
    description: 'Тёплая фотосессия в поле на закатном солнце',
    summary: 'Четыре тёплых кадра в едином образе: сидячий портрет, солнечный крупный план, взгляд назад и выразительный финальный кадр.',
    photos: 4,
    price: '189 ₽',
    category: 'lifestyle',
    categoryLabel: 'Lifestyle',
    image: '/package-previews/sp013-golden-field-model-a-hc001.jpg',
    gallery: [
      '/package-previews/sp013-golden-field-model-a-hc001.jpg',
      '/package-previews/sp013-golden-field-model-a-hc002.jpg',
      '/package-previews/sp013-golden-field-model-a-hc003.jpg',
      '/package-previews/sp013-golden-field-model-a-hc004.jpg',
    ],
    suitableFor: ['Соцсети', 'Личный бренд', 'Летний контент', 'Профиль'],
    features: ['4 профессиональных фото', 'Один цельный образ', 'Тёплый направленный свет', 'Сохранение внешности'],
    deliverables: ['Сидячий портрет', 'Солнечный крупный план', 'Взгляд назад', 'Финальный портрет'],
  },
  {
    id: 'black-minimalism',
    slug: 'black-minimalism',
    title: 'Чёрный минимализм',
    description: 'Современная деловая студийная серия в чёрном костюме',
    summary: 'Четыре камерных деловых портрета с направленным геометричным светом: главный поясной кадр, портрет в кресле и два спокойных диванных ракурса.',
    photos: 4,
    price: '189 ₽',
    category: 'business',
    categoryLabel: 'Работа',
    image: '/package-previews/sp014-black-minimalism-model-c-hc003.jpg',
    gallery: [
      '/package-previews/sp014-black-minimalism-model-c-hc003.jpg',
      '/package-previews/sp014-black-minimalism-model-c-hc001.jpg',
      '/package-previews/sp014-black-minimalism-model-c-hc002.jpg',
      '/package-previews/sp014-black-minimalism-model-c-hc004.jpg',
    ],
    suitableFor: ['Резюме', 'Личный бренд', 'Экспертный профиль', 'Соцсети'],
    features: ['4 профессиональных фото', 'Единый чёрный деловой образ', 'Камерная сидячая серия', 'Сохранение внешности'],
    deliverables: ['Главный портрет', 'Портрет в кресле', 'Диванный портрет по пояс', 'Живой деловой финал'],
  },
  {
    id: 'scarlet-accent',
    slug: 'scarlet-accent',
    title: 'Алый акцент',
    description: 'Современная студийная серия с выразительными красными деталями',
    summary: 'Четыре редакционных кадра в светлом платье на глубоком тёмно-синем фоне: крупный портрет, стоящий кадр, портрет на стуле и финал на полу.',
    photos: 4,
    price: '189 ₽',
    category: 'fashion',
    categoryLabel: 'Fashion',
    image: '/package-previews/sp015-scarlet-accent-model-b-hc004.jpg',
    gallery: [
      '/package-previews/sp015-scarlet-accent-model-b-hc004.jpg',
      '/package-previews/sp015-scarlet-accent-model-b-hc001.jpg',
      '/package-previews/sp015-scarlet-accent-model-b-hc002.jpg',
      '/package-previews/sp015-scarlet-accent-model-b-hc003.jpg',
    ],
    suitableFor: ['Соцсети', 'Fashion', 'Портфолио', 'Личный бренд'],
    features: ['4 профессиональных фото', 'Выразительный алый акцент', 'Редакционный студийный свет', 'Сохранение внешности'],
    deliverables: ['Крупный портрет', 'Стоящий editorial', 'Портрет на стуле', 'Финальный кадр'],
  },
  {
    id: 'turquoise-wave',
    slug: 'turquoise-wave',
    title: 'Бирюзовая волна',
    description: 'Свежая фотосессия на SUP в прозрачной бирюзовой воде',
    summary: 'Четыре связанных летних кадра в едином спортивном образе: съёмка на доске, портрет в воде, кадр рядом с SUP и выразительный вид сверху.',
    photos: 4,
    price: '189 ₽',
    category: 'travel',
    categoryLabel: 'Путешествия',
    image: '/package-previews/sp016-turquoise-wave-model-b-hc001.jpg',
    gallery: [
      '/package-previews/sp016-turquoise-wave-model-b-hc001.jpg',
      '/package-previews/sp016-turquoise-wave-model-b-hc002.jpg',
      '/package-previews/sp016-turquoise-wave-model-b-hc003.jpg',
      '/package-previews/sp016-turquoise-wave-model-b-hc004.jpg',
    ],
    suitableFor: ['Отпуск', 'Соцсети', 'Летний контент', 'Lifestyle'],
    features: ['4 профессиональных фото', 'Один цельный образ', 'Бирюзовая вода и солнечный свет', 'Сохранение внешности'],
    deliverables: ['Кадр на SUP', 'Портрет в воде', 'Портрет с доской', 'Кадр сверху'],
  },
  {
    id: 'pink-manifesto',
    slug: 'pink-manifesto',
    title: 'Розовый манифест',
    description: 'Современная fashion-серия в пудрово-розовом костюме',
    summary: 'Четыре связанных редакционных кадра в светлой студии: близкий портрет, живой жест у волос, игривая низкая поза и выразительный финал на прозрачном стуле с fashion-журналами.',
    photos: 4,
    price: '189 ₽',
    category: 'fashion',
    categoryLabel: 'Fashion',
    image: '/package-previews/sp019-pink-manifesto-model-b-hc004.jpg',
    gallery: [
      '/package-previews/sp019-pink-manifesto-model-b-hc004.jpg',
      '/package-previews/sp019-pink-manifesto-model-b-hc001.jpg',
      '/package-previews/sp019-pink-manifesto-model-b-hc002.jpg',
      '/package-previews/sp019-pink-manifesto-model-b-hc003.jpg',
    ],
    suitableFor: ['Соцсети', 'Fashion', 'Личный бренд', 'Портфолио'],
    features: ['4 профессиональных фото', 'Единый пудрово-розовый образ', 'Живая редакционная подача', 'Сохранение внешности'],
    deliverables: ['Финал на стуле с журналами', 'Близкий портрет', 'Beauty-портрет', 'Ростовой fashion-кадр'],
  },
  {
    id: 'make-a-wish',
    slug: 'make-a-wish',
    title: 'Загадай желание',
    description: 'Светлая праздничная серия с тортом и одной свечой',
    summary: 'Четыре праздничных портрета с небольшим светлым тортом: живое удивление, подача торта, момент перед задуванием свечи и тёплый финал после желания.',
    photos: 4,
    price: '189 ₽',
    category: 'lifestyle',
    categoryLabel: 'Lifestyle',
    image: '/package-previews/sp021-make-a-wish-model-b-hc001.jpg',
    gallery: [
      '/package-previews/sp021-make-a-wish-model-b-hc001.jpg',
      '/package-previews/sp021-make-a-wish-model-b-hc002.jpg',
      '/package-previews/sp021-make-a-wish-model-b-hc003.jpg',
      '/package-previews/sp021-make-a-wish-model-b-hc004.jpg',
    ],
    suitableFor: ['День рождения', 'Соцсети', 'Подарок', 'Личный архив'],
    features: ['4 профессиональных фото', 'Праздничный образ', 'Одна свеча без цифр', 'Сохранение внешности'],
    deliverables: ['Праздничный hero-кадр', 'Портрет с тортом', 'Момент желания', 'Финал после свечи'],
  },
  {
    id: 'first-impression',
    slug: 'first-impression',
    title: 'Первое впечатление',
    description: 'Живая профессиональная фотосессия в современном городском кафе',
    summary: 'Четыре связанных деловых lifestyle-кадра в светло-бежевом жакете: главный портрет, десертный момент и два спокойных кофейных ракурса.',
    photos: 4,
    price: '189 ₽',
    category: 'business',
    categoryLabel: 'Работа',
    image: '/package-previews/sp017-first-impression-model-c-hc003.jpg',
    gallery: [
      '/package-previews/sp017-first-impression-model-c-hc003.jpg',
      '/package-previews/sp017-first-impression-model-c-hc001.jpg',
      '/package-previews/sp017-first-impression-model-c-hc002.jpg',
      '/package-previews/sp017-first-impression-model-c-hc004.jpg',
    ],
    suitableFor: ['Личный бренд', 'Соцсети', 'Знакомства', 'Экспертный профиль'],
    features: ['4 профессиональных фото', 'Единый светлый деловой образ', 'Живая атмосфера кафе', 'Сохранение внешности'],
    deliverables: ['Кофейный hero-портрет', 'Момент с десертом', 'Портрет в кресле', 'Кадр у окна'],
  },
  {
    id: 'quiet-confidence',
    slug: 'quiet-confidence',
    title: 'Спокойная уверенность',
    description: 'Современная спокойная personal-brand серия в светлом минималистичном интерьере',
    summary: 'Четыре связанных естественных портрета в светло-голубой рубашке и тёмно-синих брюках: сидячий hero-кадр, близкий портрет, живой момент и спокойный финал.',
    photos: 4,
    price: '189 ₽',
    category: 'business',
    categoryLabel: 'Работа',
    image: '/package-previews/sp020-quiet-confidence-model-c-hc002.jpg',
    gallery: [
      '/package-previews/sp020-quiet-confidence-model-c-hc002.jpg',
      '/package-previews/sp020-quiet-confidence-model-c-hc001.jpg',
      '/package-previews/sp020-quiet-confidence-model-c-hc003.jpg',
      '/package-previews/sp020-quiet-confidence-model-c-hc004.jpg',
    ],
    suitableFor: ['Личный бренд', 'Соцсети', 'Знакомства', 'Экспертный профиль'],
    features: ['4 профессиональных фото', 'Единый современный образ', 'Светлый минималистичный интерьер', 'Сохранение внешности'],
    deliverables: ['Сидячий hero-портрет', 'Близкий портрет', 'Живой портрет', 'Спокойный финал'],
  },
  {
    id: 'petersburg-walk-v2',
    slug: 'petersburg-walk-v2',
    title: 'Прогулка в Санкт-Петербурге',
    description: 'Атмосферная городская фотосессия после дождя на улицах Санкт-Петербурга',
    summary: 'Четыре связанных городских кадра в едином светлом образе: набережная, дождливая улица, кофейная прогулка и архитектурный финал.',
    photos: 4,
    price: '189 ₽',
    category: 'business',
    categoryLabel: 'Работа',
    image: '/package-previews/sp018-petersburg-walk-model-a-hc001.jpg',
    gallery: [
      '/package-previews/sp018-petersburg-walk-model-a-hc001.jpg',
      '/package-previews/sp018-petersburg-walk-model-a-hc002.jpg',
      '/package-previews/sp018-petersburg-walk-model-a-hc003.jpg',
      '/package-previews/sp018-petersburg-walk-model-a-hc004.jpg',
    ],
    suitableFor: ['Личный бренд', 'Соцсети', 'Знакомства', 'Экспертный профиль'],
    features: ['4 профессиональных фото', 'Единый городской образ', 'Петербург после дождя', 'Сохранение внешности'],
    deliverables: ['Портрет на набережной', 'Дождливый крупный план', 'Прогулка с кофе', 'Архитектурный финал'],
  },
  {
    id: 'golden-reflection',
    slug: 'golden-reflection',
    title: 'Золотое отражение',
    description: 'Редакционная серия с зеркалом в золотом пшеничном поле',
    summary: 'Восемь связанных кадров в золотом поле: портреты, движение и выразительные композиции с круглым зеркалом и отражением.',
    photos: 8,
    price: '369 ₽',
    category: 'fashion',
    categoryLabel: 'Fashion',
    image: '/package-previews/sp022-golden-reflection-model-b-hc001.jpg',
    gallery: [
      '/package-previews/sp022-golden-reflection-model-b-hc001.jpg',
      '/package-previews/sp022-golden-reflection-model-b-hc002.jpg',
      '/package-previews/sp022-golden-reflection-model-b-hc003.jpg',
      '/package-previews/sp022-golden-reflection-model-b-hc004.jpg',
      '/package-previews/sp022-golden-reflection-model-b-hc005.jpg',
      '/package-previews/sp022-golden-reflection-model-b-hc006.jpg',
      '/package-previews/sp022-golden-reflection-model-b-hc007.jpg',
      '/package-previews/sp022-golden-reflection-model-b-hc008.jpg',
    ],
    suitableFor: ['Соцсети', 'Fashion', 'Личный бренд', 'Портфолио'],
    features: ['8 профессиональных фото', 'Единый светлый образ', 'Круглое зеркало и золотое поле', 'Сохранение внешности'],
    deliverables: ['Портрет с зеркалом', 'Крупное отражение', 'Ростовой fashion-кадр', 'Кадр в движении', 'Четыре дополнительных ракурса'],
  },  {
    id: 'scarlet-accent-2',
    slug: 'scarlet-accent-2',
    title: 'Мезенские узоры',
    description: 'Современная русская editorial-серия с яблоком и алым мини-кокошником',
    summary: 'Четыре связанных портрета в молочно-белом платье: выразительный орнамент, красное яблоко, beauty-кадр и композиция на красном стуле.',
    photos: 4,
    price: '189 ₽',
    category: 'fashion',
    categoryLabel: 'Fashion',
    image: '/package-previews/sp023-scarlet-accent-2-model-b-hc001.jpg',
    gallery: [
      '/package-previews/sp023-scarlet-accent-2-model-b-hc001.jpg',
      '/package-previews/sp023-scarlet-accent-2-model-b-hc002.jpg',
      '/package-previews/sp023-scarlet-accent-2-model-b-hc003.jpg',
      '/package-previews/sp023-scarlet-accent-2-model-b-hc004.jpg',
    ],
    suitableFor: ['Соцсети', 'Fashion', 'Личный бренд', 'Портфолио'],
    features: ['4 профессиональных фото', 'Единое молочно-белое платье', 'Алый мини-кокошник и яблоко', 'Современный русский орнамент'],
    deliverables: ['Орнаментальный hero-кадр', 'Beauty-портрет с яблоком', 'Портрет на красном стуле', 'Editorial-финал'],
  },
  {
    id: 'autumn-lake',
    slug: 'autumn-lake',
    title: 'Осеннее отражение',
    description: 'Тёплая осенняя фотосессия у тихого озера среди золотой листвы',
    summary: 'Пять связанных осенних кадров в едином образе: игривый портрет с листом, крупный hero-кадр, портрет с шарфом, мягкий разворот у воды и спокойный атмосферный финал.',
    photos: 5,
    price: '229 ₽',
    category: 'lifestyle',
    categoryLabel: 'Lifestyle',
    image: '/package-previews/sp024-autumn-lake-model-c-hc001.jpg',
    gallery: [
      '/package-previews/sp024-autumn-lake-model-c-hc001.jpg',
      '/package-previews/sp024-autumn-lake-model-c-hc002.jpg',
      '/package-previews/sp024-autumn-lake-model-c-hc003.jpg',
      '/package-previews/sp024-autumn-lake-model-c-hc004.jpg',
      '/package-previews/sp024-autumn-lake-model-c-hc005.jpg',
    ],
    suitableFor: ['Соцсети', 'Личный бренд', 'Lifestyle', 'Сезонный контент'],
    features: ['5 профессиональных фото', 'Единый осенний образ', 'Озеро и золотая листва', 'Живой кадр с осенним листом'],
    deliverables: ['Портрет с листом', 'Крупный портрет у озера', 'Портрет с шарфом', 'Разворот у воды', 'Атмосферный финал'],
  },
  {
    id: 'autumn-route',
    slug: 'autumn-route',
    title: 'Осенний маршрут',
    description: 'Четыре стильных осенних портрета в городе, у канала и кованой ограды',
    summary: 'Четыре связанных кадра городской осенней прогулки: сидячий hero-портрет, портрет у канала, кадр в движении и спокойный lifestyle-финал.',
    photos: 4,
    price: '189 ₽',
    category: 'lifestyle',
    categoryLabel: 'Lifestyle',
    image: '/package-previews/sp025-autumn-route-model-b-hc001.jpg',
    gallery: [
      '/package-previews/sp025-autumn-route-model-b-hc001.jpg',
      '/package-previews/sp025-autumn-route-model-b-hc002.jpg',
    ],
    suitableFor: ['Соцсети', 'Lifestyle', 'Знакомства', 'Сезонный контент'],
    features: ['4 профессиональных фото', 'Единый городской образ', 'Осенняя атмосфера', 'Сохранение внешности'],
    deliverables: ['Сидячий портрет у ограды', 'Городской портрет по колени', 'Кадр в движении', 'Спокойный портрет на скамье'],
  },
  {
    id: 'misty-cabin',
    slug: 'misty-cabin',
    title: 'Дом в тумане',
    description: 'Уютная фотосессия у современного загородного дома среди леса и мягкого тумана',
    summary: 'Четыре гармоничных кадра для спокойного и атмосферного личного контента.',
    photos: 4,
    price: '189 ₽',
    category: 'lifestyle',
    categoryLabel: 'Lifestyle',
    image: '/package-previews/sp026-misty-cabin-model-b-hc001.jpg',
    gallery: [
      '/package-previews/sp026-misty-cabin-model-b-hc001.jpg',
      '/package-previews/sp026-misty-cabin-model-b-hc002.jpg',
      '/package-previews/sp026-misty-cabin-model-b-hc003.jpg',
      '/package-previews/sp026-misty-cabin-model-b-hc004.jpg',
    ],
    suitableFor: ['Соцсети', 'Lifestyle', 'Личный бренд', 'Загородный отдых'],
    features: ['4 профессиональных фото', 'Единый уютный образ', 'Современный загородный дом', 'Лес и мягкий туман'],
    deliverables: ['Сидячий портрет на террасе', 'Портрет с чашкой', 'Портрет у перил', 'Спокойный кадр на ступенях'],
  },
];

type PhotoPackEconomy = Pick<PhotoPack, 'photoCount' | 'priceRub' | 'priceCrystals'>;

const economyByPack: Record<string, PhotoPackEconomy> = {
  'autumn-promenade': { photoCount: 4, priceRub: 189, priceCrystals: 38 },
  'misty-morning': { photoCount: 4, priceRub: 189, priceCrystals: 38 },
  'golden-field': { photoCount: 4, priceRub: 189, priceCrystals: 38 },
  'black-minimalism': { photoCount: 4, priceRub: 189, priceCrystals: 38 },
  'scarlet-accent': { photoCount: 4, priceRub: 189, priceCrystals: 38 },
  'turquoise-wave': { photoCount: 4, priceRub: 189, priceCrystals: 38 },
  'pink-manifesto': { photoCount: 4, priceRub: 189, priceCrystals: 38 },
  'make-a-wish': { photoCount: 4, priceRub: 189, priceCrystals: 38 },
  'first-impression': { photoCount: 4, priceRub: 189, priceCrystals: 38 },
  'quiet-confidence': { photoCount: 4, priceRub: 189, priceCrystals: 38 },
  'petersburg-walk-v2': { photoCount: 4, priceRub: 189, priceCrystals: 38 },
  'golden-reflection': { photoCount: 8, priceRub: 369, priceCrystals: 74 },
  'scarlet-accent-2': { photoCount: 4, priceRub: 189, priceCrystals: 38 },
  'autumn-lake': { photoCount: 5, priceRub: 229, priceCrystals: 46 },
  'autumn-route': { photoCount: 4, priceRub: 189, priceCrystals: 38 },
  'misty-cabin': { photoCount: 4, priceRub: 189, priceCrystals: 38 },
  career: { photoCount: 4, priceRub: 189, priceCrystals: 38 },
  dating: { photoCount: 4, priceRub: 179, priceCrystals: 36 },
  sup: { photoCount: 6, priceRub: 279, priceCrystals: 56 },
  'studio-elegance': { photoCount: 6, priceRub: 269, priceCrystals: 54 },
  'lakeside-walk': { photoCount: 4, priceRub: 179, priceCrystals: 36 },
  'casual-park': { photoCount: 4, priceRub: 189, priceCrystals: 38 },
  'minimal-black-studio': { photoCount: 4, priceRub: 199, priceCrystals: 40 },
  'russian-editorial': { photoCount: 6, priceRub: 279, priceCrystals: 56 },
  social: { photoCount: 2, priceRub: 99, priceCrystals: 20 },
  studio: { photoCount: 6, priceRub: 269, priceCrystals: 54 },
  neon: { photoCount: 8, priceRub: 369, priceCrystals: 74 },
  bw: { photoCount: 4, priceRub: 199, priceCrystals: 40 },
};

function applyPackEconomy(
  pack: Omit<PhotoPack, 'pricing' | 'photoCount' | 'priceRub' | 'priceCrystals'>,
): PhotoPack {
  const economy = economyByPack[pack.id] ?? { photoCount: 4, priceRub: 189, priceCrystals: 38 };

  return {
    ...pack,
    ...economy,
    photos: economy.photoCount,
    price: `${economy.priceRub} ₽`,
    pricing: {
      hd: { tokens: economy.priceCrystals, rubles: economy.priceRub },
      fullHd: { tokens: economy.priceCrystals, rubles: economy.priceRub },
    },
  };
}

export const photoPacks: PhotoPack[] = currentBasePhotoPacks.map(applyPackEconomy);
const archivedPhotoPacks: PhotoPack[] = legacyBasePhotoPacks.map(applyPackEconomy);

export function getPhotoPack(slug: string) {
  return photoPacks.find((pack) => pack.slug === slug || pack.id === slug);
}

export function getPhotoPackForHistory(slug: string) {
  return getPhotoPack(slug) ?? archivedPhotoPacks.find((pack) => pack.slug === slug || pack.id === slug);
}

export function getRelatedPhotoPacks(slug: string, limit = 6) {
  const current = getPhotoPack(slug);
  const pool = current
    ? photoPacks.filter((pack) => pack.id !== current.id).sort((left, right) => {
        if (left.category === current.category && right.category !== current.category) return -1;
        if (left.category !== current.category && right.category === current.category) return 1;
        return 0;
      })
    : photoPacks;

  return pool.slice(0, limit);
}
