-- Legacy compatibility file.
--
-- The authoritative database schema now lives in:
--   supabase_schema.sql
--
-- Keep this file so old notes or bookmarks do not break, but use
-- `supabase_schema.sql` for all future database setup and updates.
--
-- Why this file exists:
-- - Older project versions used this file for the `photoshoots` table.
-- - It drifted from the real application code.
-- - The current schema has been reconciled into one source of truth.
